pull_request_rules:
  - name: Merge PRs that are ready
    conditions:
      - "#review-requested=0"
      - "#approved-reviews-by>=1"
      - label!=block-merge
      - label=dependencies
    actions:
      merge:
        method: squash
  - name: Delete the merge-when-green label after merge
    conditions:
      - merged
      - label=block-merge
    actions:
      label:
        remove:
          - block-merge
queue_rules: []
merge_queue:
  max_parallel_checks: 2
